// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stainer.Web.Infrastructure.Data;

#nullable disable

namespace Stainer.Web.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StainerDbContext))]
    [Migration("20260624021457_InitialInfrastructure")]
    partial class InitialInfrastructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");
#pragma warning restore 612, 618
        }
    }
}
