// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stainer.Web.Infrastructure.Data;

#nullable disable

namespace Stainer.Web.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StainerDbContext))]
    [Migration("20260624023135_ReferenceDataModel")]
    partial class ReferenceDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Stainer.Web.Domain.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateCalibrationHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AspirateZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aspirate_z_um");

                    b.Property<string>("CalibratedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("calibrated_by_user_id");

                    b.Property<string>("CoordinatePointId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("coordinate_point_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DispenseZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispense_z_um");

                    b.Property<long?>("NewXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_x_um");

                    b.Property<long?>("NewYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_y_um");

                    b.Property<long?>("PreviousXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_x_um");

                    b.Property<long?>("PreviousYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_y_um");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long?>("SafeZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("safe_z_um");

                    b.HasKey("Id");

                    b.HasIndex("CalibratedByUserId");

                    b.HasIndex("CoordinatePointId");

                    b.ToTable("coordinate_calibration_history", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AspirateZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aspirate_z_um");

                    b.Property<long?>("CalibratedXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calibrated_x_um");

                    b.Property<long?>("CalibratedYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calibrated_y_um");

                    b.Property<string>("CoordinateProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("coordinate_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DispenseZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispense_z_um");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("PointCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_code");

                    b.Property<string>("PointType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_type");

                    b.Property<long?>("PresetXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_x_um");

                    b.Property<long?>("PresetYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_y_um");

                    b.Property<bool>("RequiresCalibration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_calibration");

                    b.Property<long?>("SafeZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("safe_z_um");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateProfileId", "PointCode")
                        .IsUnique();

                    b.ToTable("coordinate_points", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OriginDefinition")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin_definition");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("coordinate_profiles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.DabMixPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_no");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PositionNo")
                        .IsUnique();

                    b.ToTable("dab_mix_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.DeviceProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("device_profiles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Drawer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("HeatBoardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heat_board_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HeatBoardId")
                        .IsUnique();

                    b.ToTable("drawers", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PhysicalSlot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DrawerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("drawer_id");

                    b.Property<int>("HeatPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heat_point_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<int>("VerticalOrderFromBottom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vertical_order_from_bottom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DrawerId", "HeatPointId")
                        .IsUnique();

                    b.HasIndex("DrawerId", "SlotNo")
                        .IsUnique();

                    b.ToTable("physical_slots", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentRackPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<int>("ColumnNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("column_no");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_no");

                    b.Property<int>("RowNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_no");

                    b.Property<string>("ScannerChannelCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("scanner_channel_code");

                    b.Property<int>("ScannerChannelNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scanner_channel_no");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PositionNo")
                        .IsUnique();

                    b.HasIndex("ColumnNo", "RowNo")
                        .IsUnique();

                    b.ToTable("reagent_rack_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WashPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("WashType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("wash_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("wash_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateCalibrationHistory", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.User", "CalibratedByUser")
                        .WithMany()
                        .HasForeignKey("CalibratedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stainer.Web.Domain.Entities.CoordinatePoint", "CoordinatePoint")
                        .WithMany("CalibrationHistory")
                        .HasForeignKey("CoordinatePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalibratedByUser");

                    b.Navigation("CoordinatePoint");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.CoordinateProfile", "CoordinateProfile")
                        .WithMany("CoordinatePoints")
                        .HasForeignKey("CoordinateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateProfile");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PhysicalSlot", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.Drawer", "Drawer")
                        .WithMany("PhysicalSlots")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stainer.Web.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.Navigation("CalibrationHistory");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateProfile", b =>
                {
                    b.Navigation("CoordinatePoints");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Drawer", b =>
                {
                    b.Navigation("PhysicalSlots");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
